---
title: "Manuel Alcalá Kovalski's CV"
author: Manuel Alcalá Kovalski
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css','custom.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object

CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1XTvyiIEKFMMvLIQnL5shIUXv2_Y1atyEqZNkEUtZIs4/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```
<!-- inicio font awesome -->
<script src="https://kit.fontawesome.com/1f72d6921a.js" crossorigin="anonymous"></script>


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```

```{r}
if(params$pdf_mode){
  #cat("View this CV online with links at _nickstrayer.me/datadrivencv/_")
} else {
  cat(" ")
  # cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/malcalakovalski/cv/raw/master/alcala_kovalski_cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```

Software {#software}
--------------------------------------------------------------------------------

<i class="fas fa-box-open"></i> [Package {ggbrookings}](https://brookingsinstitution.github.io/ggbrookings/) - Author, maintainer. 


Programming skills {#skills}
--------------------------------------------------------------------------------

<i class="fab fa-r-project"></i> `R`

<i class="fa fa-area-chart" aria-hidden="true"></i>
 `tidyverse`

<i class="fas fa-code-branch"></i> `Git`

<i class="fab fa-github"></i> `GitHub`

<i class='fab fa-markdown fa-fw fa-1x'></i> `Markdown`

<i class="fab fa-html5"></i> `HTML`

<i class="fab fa-css3-alt"></i> `CSS`



Main
================================================================================

Manuel Alcalá Kovalski {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education', resume = TRUE)
```



Work Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('work_experience', resume = TRUE)
```



Publications
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('academic_articles', resume = TRUE)
```



```{r}
# CV %<>% print_links()
```

