name: update-site

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install package dependencies
        run:
          Rscript -e "install.packages(c('tidyverse', 'rmarkdown', 'pagedown'))"
      - name: Render index file
        run:
          Rscript -e "source('index.Rmd')"
      - name: Commit results
        run: |
          git add index.html
          git commit -m 'Re-build site'
          git push origin
